# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import jusutils.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Header Name')),
                ('slug', models.SlugField(blank=True, help_text='Used for calling models in templates', max_length=150, verbose_name='Name Slug')),
                ('html_ids', models.CharField(blank=True, max_length=120, verbose_name='HTML Id')),
                ('html_class', models.CharField(blank=True, max_length=200, verbose_name='HTML Class')),
                ('template', models.CharField(default='footer.html', max_length=250, verbose_name='Template')),
                ('content', models.TextField(blank=True, verbose_name='HTML Content')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footers',
            },
            bases=(jusutils.mixins.SingleInstanceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Header Name')),
                ('slug', models.SlugField(blank=True, help_text='Used for calling models in templates', max_length=150, verbose_name='Name Slug')),
                ('html_ids', models.CharField(blank=True, max_length=120, verbose_name='HTML Id')),
                ('html_class', models.CharField(blank=True, max_length=200, verbose_name='HTML Class')),
                ('template', models.CharField(default='header.html', max_length=250, verbose_name='Template')),
                ('content', models.TextField(blank=True, verbose_name='HTML Content')),
            ],
            options={
                'verbose_name': 'Header',
                'verbose_name_plural': 'Headers',
            },
            bases=(jusutils.mixins.SingleInstanceMixin, models.Model),
        ),
    ]
