# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-05 05:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='template',
        ),
        migrations.RemoveField(
            model_name='header',
            name='template',
        ),
    ]
