# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_id', models.CharField(blank=True, max_length=60, verbose_name='HTML ID')),
                ('html_class', models.CharField(blank=True, max_length=120, verbose_name='HTML Class')),
                ('template', models.CharField(default='pages/chunk.html', max_length=300, verbose_name='HTML Template')),
                ('content', models.TextField(blank=True, verbose_name='HTML Content')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Page Title')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Page URL Slug')),
                ('path', models.CharField(blank=True, max_length=800, unique=True, verbose_name='Page URL Path')),
                ('seo_title', models.CharField(blank=True, max_length=120, verbose_name='Page SEO Title')),
                ('seo_description', models.CharField(blank=True, max_length=255, verbose_name='Page SEO Description')),
                ('template', models.CharField(default='page.html', max_length=300, verbose_name='Template File Path')),
                ('is_home', models.BooleanField(default=False, help_text='This will override the current home page.', verbose_name='Set this page as home page?')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.Page', verbose_name='Parent Page')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html_id', models.CharField(blank=True, max_length=60, verbose_name='HTML ID')),
                ('html_class', models.CharField(blank=True, max_length=120, verbose_name='HTML Class')),
                ('template', models.CharField(default='pages/row.html', max_length=300, verbose_name='HTML Template')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pages.Page', verbose_name='Parent Page')),
            ],
            options={
                'verbose_name': 'Row',
                'verbose_name_plural': 'Rows',
            },
        ),
        migrations.AddField(
            model_name='chunk',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='pages.Row', verbose_name='Parent Row'),
        ),
    ]
