# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20160117_0133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chunk',
            old_name='html_id',
            new_name='html_ids',
        ),
        migrations.RenameField(
            model_name='row',
            old_name='html_id',
            new_name='html_ids',
        ),
    ]
